#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="${PROJECT_DIR}/src"

mkdir -p "${OUT_DIR}"

CONFIG_PATH_DEFAULT="src/user_config.yml"
if [[ ! -f "${PROJECT_DIR}/${CONFIG_PATH_DEFAULT}" ]]; then
  echo "Error: missing ${CONFIG_PATH_DEFAULT}. Expected at ${PROJECT_DIR}/${CONFIG_PATH_DEFAULT}" >&2
  exit 1
fi

# pei-docker-cli requires compose-template.yml at the project root.
# Keep it tracked under src/ and create a temporary symlink for the duration of this script.
TEMP_ROOT_COMPOSE_TEMPLATE_LINK=0
if [[ ! -f "${OUT_DIR}/compose-template.yml" ]]; then
  echo "Error: missing src/compose-template.yml. Expected at ${OUT_DIR}/compose-template.yml" >&2
  exit 1
fi

# pei-docker-cli writes stage generated artifacts under installation/stage-*/...
# Keep the repo root clean by creating a temporary symlink for the duration of this script.
TEMP_ROOT_INSTALLATION_LINK=0
cleanup() {
  if [[ "${TEMP_ROOT_COMPOSE_TEMPLATE_LINK}" == "1" ]]; then
    rm -f "${PROJECT_DIR}/compose-template.yml" || true
  fi
  if [[ "${TEMP_ROOT_INSTALLATION_LINK}" == "1" ]]; then
    rm -f "${PROJECT_DIR}/installation" || true
  fi
}
trap cleanup EXIT

if [[ -e "${PROJECT_DIR}/compose-template.yml" && ! -L "${PROJECT_DIR}/compose-template.yml" ]]; then
  echo "Error: ${PROJECT_DIR}/compose-template.yml exists and is not a symlink. Refusing to overwrite." >&2
  echo "Move it to ${OUT_DIR}/compose-template.yml (or remove it) and re-run." >&2
  exit 1
fi
if [[ ! -e "${PROJECT_DIR}/compose-template.yml" ]]; then
  ln -s "src/compose-template.yml" "${PROJECT_DIR}/compose-template.yml"
  TEMP_ROOT_COMPOSE_TEMPLATE_LINK=1
fi

if [[ -e "${PROJECT_DIR}/installation" && ! -L "${PROJECT_DIR}/installation" ]]; then
  echo "Error: ${PROJECT_DIR}/installation exists and is not a symlink. Refusing to overwrite." >&2
  echo "Move it to ${PROJECT_DIR}/src/installation (or remove it) and re-run." >&2
  exit 1
fi
if [[ ! -e "${PROJECT_DIR}/installation" ]]; then
  ln -s "src/installation" "${PROJECT_DIR}/installation"
  TEMP_ROOT_INSTALLATION_LINK=1
fi

EXTRA_ARGS=()
HAS_CONFIG_FLAG=0
for arg in "$@"; do
  if [[ "$arg" == "-c" || "$arg" == "--config" ]]; then
    HAS_CONFIG_FLAG=1
    break
  fi
done
if [[ "${HAS_CONFIG_FLAG}" == "0" ]]; then
  EXTRA_ARGS+=( -c "${CONFIG_PATH_DEFAULT}" )
fi

pixi run pei-docker-cli configure -p "${PROJECT_DIR}" "${EXTRA_ARGS[@]}" "$@"

move_if_exists() {
  local name="$1"
  if [[ -e "${PROJECT_DIR}/${name}" ]]; then
    mv -f "${PROJECT_DIR}/${name}" "${OUT_DIR}/${name}"
  fi
}

# Root-level artifacts generated by `pei-docker-cli configure` / `--with-merged`.
move_if_exists "docker-compose.yml"
move_if_exists "PEI-DOCKER-USAGE-GUIDE.md"
move_if_exists "stage-1.Dockerfile"
move_if_exists "stage-2.Dockerfile"
move_if_exists "merged.Dockerfile"
move_if_exists "merged.env"
move_if_exists "build-merged.sh"
move_if_exists "run-merged.sh"

patch_compose_paths() {
  local compose_path="${OUT_DIR}/docker-compose.yml"
  [[ -f "${compose_path}" ]] || return 0

  python3 - "${compose_path}" <<'PY'
import re
import sys
from pathlib import Path

path = Path(sys.argv[1])
text = path.read_text()

# Ensure a stable project name (avoid "src_default" etc).
lines = text.splitlines()
if not lines or not lines[0].startswith("name:"):
    text = "name: model-bench-cu128\n\n" + text.lstrip("\n")

# When docker-compose.yml lives under src/, relative paths must refer to the parent directory.
text = re.sub(r"(?m)^(\s*context:\s*)\.$", r"\1..", text)
text = re.sub(
    r"(?m)^(\s*dockerfile:\s*)(\./)?(\.\./)?stage-1\.Dockerfile\s*$",
    r"\1src/stage-1.Dockerfile",
    text,
)
text = re.sub(
    r"(?m)^(\s*dockerfile:\s*)(\./)?(\.\./)?stage-2\.Dockerfile\s*$",
    r"\1src/stage-2.Dockerfile",
    text,
)
text = re.sub(r"(?m)^(\s*-\s*)(\./)?\.container/", r"\1../.container/", text)
text = text.replace("PEI_STAGE_HOST_DIR_1: ./installation/stage-1", "PEI_STAGE_HOST_DIR_1: ./src/installation/stage-1")
text = text.replace("PEI_STAGE_HOST_DIR_2: ./installation/stage-2", "PEI_STAGE_HOST_DIR_2: ./src/installation/stage-2")

path.write_text(text)
PY
}

patch_build_merged_context() {
  local script_path="${OUT_DIR}/build-merged.sh"
  [[ -f "${script_path}" ]] || return 0

  python3 - "${script_path}" <<'PY'
import sys
from pathlib import Path

path = Path(sys.argv[1])
text = path.read_text().splitlines()

if any(line.startswith("PROJECT_ROOT=") for line in text):
    raise SystemExit(0)

out = []
for line in text:
    out.append(line)
    if line.startswith("PROJECT_DIR="):
        out.append('PROJECT_ROOT=$(cd "$PROJECT_DIR/.." && pwd)')

new = "\n".join(out) + "\n"
new = new.replace('cmd+=( "$PROJECT_DIR" )', 'cmd+=( "$PROJECT_ROOT" )')
path.write_text(new)
PY
  chmod +x "${script_path}" || true
}

patch_merged_env_paths() {
  local env_path="${OUT_DIR}/merged.env"
  [[ -f "${env_path}" ]] || return 0

  python3 - "${env_path}" <<'PY'
import sys
from pathlib import Path

path = Path(sys.argv[1])
text = path.read_text()

text = text.replace("PEI_STAGE_HOST_DIR_1='./installation/stage-1'", "PEI_STAGE_HOST_DIR_1='./src/installation/stage-1'")
text = text.replace("PEI_STAGE_HOST_DIR_2='./installation/stage-2'", "PEI_STAGE_HOST_DIR_2='./src/installation/stage-2'")

path.write_text(text)
PY
}

patch_usage_guide() {
  local guide_path="${OUT_DIR}/PEI-DOCKER-USAGE-GUIDE.md"
  [[ -f "${guide_path}" ]] || return 0

  python3 - "${guide_path}" <<'PY'
import re
import sys
from pathlib import Path

path = Path(sys.argv[1])
text = path.read_text()

text = text.replace("`docker-compose.yml`", "`src/docker-compose.yml`")
text = text.replace("pei-docker-cli configure", "./pei-configure.sh")
text = text.replace("`build-merged.sh`", "`src/build-merged.sh`")
text = text.replace("./build-merged.sh", "./src/build-merged.sh")
text = text.replace("./run-merged.sh", "./src/run-merged.sh")
text = text.replace("`user_config.yml`", "`src/user_config.yml`")
text = text.replace("Edit `user_config.yml`", "Edit `src/user_config.yml`")
text = text.replace("Edit `user_config.yml`.", "Edit `src/user_config.yml`.")
text = re.sub(r"(?<!src/)installation/", "src/installation/", text)

text = text.replace("docker compose build stage-2", "docker compose -f src/docker-compose.yml build stage-2")
text = text.replace("docker compose build stage-1", "docker compose -f src/docker-compose.yml build stage-1")
text = text.replace("docker compose up -d", "docker compose -f src/docker-compose.yml up -d")
text = text.replace("docker compose up", "docker compose -f src/docker-compose.yml up")

path.write_text(text)
PY
}

patch_compose_paths
patch_build_merged_context
patch_merged_env_paths
patch_usage_guide

echo "OK: moved generated artifacts into ${OUT_DIR}"
