#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="${PROJECT_DIR}/src"
DELTA_DIR="${PROJECT_DIR}/delta"
DELTA_POST_CREATE_DIR="${DELTA_DIR}/post-create"
DELTA_POST_CONFIGURE_DIR="${DELTA_DIR}/post-configure"

usage() {
  cat <<'USAGE'
Usage:
  pei-configure.sh [--apply-post-create] [--apply-post-configure] [pei-docker-cli configure args...]

Default behavior (no --apply-* flags):
  Apply post-create -> run pei-docker-cli configure -> apply post-configure.

Notes:
  - src/ must be generated by: pixi run pei-docker-cli create -p ./src
  - Canonical config lives at delta/post-create/user_config.persist.yml
USAGE
}

die() {
  echo "Error: $*" >&2
  exit 1
}

require_path() {
  local p="$1"
  [[ -e "${p}" ]] || die "missing required path: ${p}"
}

require_file() {
  local p="$1"
  [[ -f "${p}" ]] || die "missing required file: ${p}"
}

copy_file() {
  local src="$1"
  local dst="$2"
  mkdir -p "$(dirname -- "${dst}")"
  cp -f "${src}" "${dst}"
}

apply_overlay_dir() {
  local overlay_root="$1"
  local dst_root="$2"
  local mode="$3" # post-create | post-configure

  [[ -d "${overlay_root}" ]] || return 0

  while IFS= read -r -d '' src_path; do
    local rel="${src_path#${overlay_root}/}"
    local dst_path="${dst_root}/${rel}"

    # Skip canonical config: handled explicitly.
    if [[ "${mode}" == "post-create" && "${rel}" == "user_config.persist.yml" ]]; then
      continue
    fi

    # For post-configure we only allow file overlays (no directories).
    if [[ -d "${src_path}" ]]; then
      continue
    fi

    if [[ "${mode}" == "post-create" ]]; then
      if [[ "${rel}" == installation/stage-*/custom/* ]]; then
        copy_file "${src_path}" "${dst_path}"
        continue
      fi

      # Any override outside custom/ must already exist in src/ (template mismatch check).
      [[ -e "${dst_path}" ]] || die "template/version mismatch: ${dst_path} does not exist (from delta/post-create/${rel})"
      copy_file "${src_path}" "${dst_path}"
      continue
    fi

    if [[ "${mode}" == "post-configure" ]]; then
      [[ -e "${dst_path}" ]] || die "configure output mismatch: ${dst_path} does not exist (from delta/post-configure/${rel})"
      copy_file "${src_path}" "${dst_path}"
      continue
    fi
  done < <(find "${overlay_root}" -type f -print0)
}

apply_post_create() {
  require_path "${SRC_DIR}"
  require_file "${SRC_DIR}/compose-template.yml"
  require_file "${SRC_DIR}/reference_config.yml"
  require_path "${SRC_DIR}/installation/stage-1"
  require_path "${SRC_DIR}/installation/stage-2"
  require_file "${DELTA_POST_CREATE_DIR}/user_config.persist.yml"

  # Canonical config -> src/user_config.yml
  copy_file "${DELTA_POST_CREATE_DIR}/user_config.persist.yml" "${SRC_DIR}/user_config.yml"

  # Overlay other files.
  apply_overlay_dir "${DELTA_POST_CREATE_DIR}" "${SRC_DIR}" "post-create"
}

apply_post_configure() {
  require_path "${SRC_DIR}"
  [[ -d "${DELTA_POST_CONFIGURE_DIR}" ]] || return 0

  apply_overlay_dir "${DELTA_POST_CONFIGURE_DIR}" "${SRC_DIR}" "post-configure"
}

run_configure() {
  require_path "${SRC_DIR}"
  (cd "${SRC_DIR}" && pixi run pei-docker-cli configure "$@")
}

APPLY_POST_CREATE=0
APPLY_POST_CONFIGURE=0
FORWARD=()

for arg in "$@"; do
  case "${arg}" in
    -h|--help)
      usage
      exit 0
      ;;
    --apply-post-create)
      APPLY_POST_CREATE=1
      ;;
    --apply-post-configure)
      APPLY_POST_CONFIGURE=1
      ;;
    *)
      FORWARD+=( "${arg}" )
      ;;
  esac
done

if [[ "${APPLY_POST_CREATE}" == "0" && "${APPLY_POST_CONFIGURE}" == "0" ]]; then
  # Full pipeline by default.
  apply_post_create
  run_configure "${FORWARD[@]}"
  apply_post_configure
  echo "OK: applied post-create + configured + applied post-configure"
  exit 0
fi

if [[ "${APPLY_POST_CREATE}" == "1" ]]; then
  apply_post_create
  echo "OK: applied post-create delta"
fi

if [[ "${APPLY_POST_CONFIGURE}" == "1" ]]; then
  apply_post_configure
  echo "OK: applied post-configure delta"
fi
