#!/usr/bin/env bash
set -euo pipefail

PROJECT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="${PROJECT_DIR}/src"

mkdir -p "${OUT_DIR}"

pei-docker-cli configure -p "${PROJECT_DIR}" "$@"

move_if_exists() {
  local name="$1"
  if [[ -e "${PROJECT_DIR}/${name}" ]]; then
    mv -f "${PROJECT_DIR}/${name}" "${OUT_DIR}/${name}"
  fi
}

# Root-level artifacts generated by `pei-docker-cli configure` / `--with-merged`.
move_if_exists "docker-compose.yml"
move_if_exists "PEI-DOCKER-USAGE-GUIDE.md"
move_if_exists "merged.Dockerfile"
move_if_exists "merged.env"
move_if_exists "build-merged.sh"

patch_compose_paths() {
  local compose_path="${OUT_DIR}/docker-compose.yml"
  [[ -f "${compose_path}" ]] || return 0

  python3 - "${compose_path}" <<'PY'
import sys
from pathlib import Path

path = Path(sys.argv[1])
text = path.read_text()

# Ensure a stable project name (avoid "src_default" etc).
lines = text.splitlines()
if not lines or not lines[0].startswith("name:"):
    text = "name: infer-dev\n\n" + text.lstrip("\n")

# When docker-compose.yml lives under src/, relative paths must refer to the parent directory.
text = text.replace("context: .", "context: ..")
text = text.replace("dockerfile: ../stage-1.Dockerfile", "dockerfile: stage-1.Dockerfile")
text = text.replace("dockerfile: ../stage-2.Dockerfile", "dockerfile: stage-2.Dockerfile")
text = text.replace("- .container/", "- ../.container/")

path.write_text(text)
PY
}

patch_build_merged_context() {
  local script_path="${OUT_DIR}/build-merged.sh"
  [[ -f "${script_path}" ]] || return 0

  python3 - "${script_path}" <<'PY'
import sys
from pathlib import Path

path = Path(sys.argv[1])
text = path.read_text().splitlines()

out = []
has_root = False
for line in text:
    out.append(line)
    if line.startswith("PROJECT_DIR=") and not has_root:
        out.append('PROJECT_ROOT=$(cd "$PROJECT_DIR/.." && pwd)')
        has_root = True

new = "\n".join(out) + "\n"
new = new.replace('cmd+=( "$PROJECT_DIR" )', 'cmd+=( "$PROJECT_ROOT" )')
path.write_text(new)
PY
  chmod +x "${script_path}" || true
}

patch_usage_guide() {
  local guide_path="${OUT_DIR}/PEI-DOCKER-USAGE-GUIDE.md"
  [[ -f "${guide_path}" ]] || return 0

  python3 - "${guide_path}" <<'PY'
import sys
from pathlib import Path

path = Path(sys.argv[1])
text = path.read_text()

text = text.replace("`docker-compose.yml`", "`src/docker-compose.yml`")
text = text.replace("pei-docker-cli configure", "./pei-configure.sh")
text = text.replace("`build-merged.sh`", "`src/build-merged.sh`")
text = text.replace("./build-merged.sh", "./src/build-merged.sh")

text = text.replace("docker compose build stage-2", "docker compose -f src/docker-compose.yml build stage-2")
text = text.replace("docker compose build stage-1", "docker compose -f src/docker-compose.yml build stage-1")
text = text.replace("docker compose up -d", "docker compose -f src/docker-compose.yml up -d")
text = text.replace("docker compose up", "docker compose -f src/docker-compose.yml up")

path.write_text(text)
PY
}

patch_compose_paths
patch_build_merged_context
patch_usage_guide

echo "OK: moved generated artifacts into ${OUT_DIR}"
